<a href="https://colab.research.google.com/github/jqc-prof/DL/blob/main/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

#generate a matrix of 12 32 float digits 0-11
x = torch.arange(12, dtype=torch.float32)
x.numel()
x.shape
X = x.reshape(3,4)

#Slicing
#Access last row (-1) and rows 1-3
X[-1], X[0:3]

#Set matrix of 3rd row 3rd column to 13
X[2, 2] = 13
X

#For instance, [:2, :] accesses the first and second rows, where : takes
#all the elements along axis 1 (column).
X[:2, :] = 9
X

#turn values into probabilities for classifiers using exp() which is basically
#e^xi
torch.exp(x)

tensor([  8103.0840,   8103.0840,   8103.0840,   8103.0840,   8103.0840,
          8103.0840,   8103.0840,   8103.0840,   2980.9580,   8103.0840,
        442413.4062,  59874.1406])

In [ ]:
#scalar manipulation
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

#We can also concatenate multiple tensors, stacking them end-to-end to
#form a larger one
X2 = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

#dim=0 stacks them vertically adding more rows torch.cat(((2,3),(3,3)), dim=0)
#results in dimensions (5,3) and torch.cat(((2,3),(2,3)), dim=1). (axis0, axis1)
#results in (2,6)
torch.cat((X2, Y), dim=0), torch.cat((X2, Y), dim=1)

#checks to see what indexes of matrix 1 and 2 match
X2 == Y
#summation
X.sum()

tensor(256.)

In [ ]:
#Broadcasting expands one or both arrays by copying elements along axes with
#length 1 so that after this transformation, the two tensors have the same shape
#then performs elementwise operation on the resulting arrays.
#it is meant to multiple vectors of 2 differing lengths.
#a = torch.arange(3).reshape((3, -1))
#b = torch.arange(2).reshape((-1, 2))

a = torch.arange(24).reshape((2,3,4))
b = torch.arange(24).reshape((2,3,-1))

a, b
#produces a 3x2 matrix by replicating matrix a along columns and matrix b along
#the rows before adding them elementwise.
a+b

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [ ]:
#memory saving techniques
#if we do Y = X + Y, Y becomes allocated to a new position in memory.
#It first evaluates X + Y and assigns it to a new location.
#id(Y) locates the position of the Y tensor in memory.
before = id(Y)
Y = Y + X
id(Y) == before

#we dont want to allocate memory all over the place,
#we need to perform these updates in place. it causes an issue where multiple
#variables point to the same parameters. update references or cause memory leak

#in-place operations can be performed by using slice:
Z = torch.zeros_like(Y)
print('id(Z): ', id(Z))
Z[:] = X + Y
print('id(Z): ', id(Z))

#If X is not reused in subsequent computations we can also use X[:] = X + Y
#or X += Y to reduce memory overhead of the operation
before = id(X)
X += Y
id(X) == before

id(Z):  135477633441936
id(Z):  135477633441936


True

In [ ]:
#Tensor/matrix generation
torch.zeros((2,3,4))
torch.ones((2,3,4))
#The following snippet creates
#a tensor with elements drawn from a standard Gaussian (normal)
#distribution with mean 0 and standard deviation 1.
torch.randn(3,4)
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
#Object conversion
#Conversion to a NumPy tensor (ndarray)
#The torch tensor and NumPy array will share their underlying memory,
#and changing one through an in-place operation will also change the other.
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)
#conversion
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)