<a href="https://colab.research.google.com/github/jqc-prof/DL/blob/main/LinearAlgebraIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Scalars
#scalars are denoted as lower-cased letters
#scalars are implemented as tensors with only 1 element
import torch
x = torch.tensor(3)
y = torch.tensor(2)
x+y,x*y,x/y,x**y

#Vectors
#fixed-length array of scalars also known as elements of the vector
#vectors are 1st-order tensors
#vectors start at indicies 0 zero-based indexing in python
#linear algebra subscripts start at 1
x = torch.arange(3)
x
x[2] #tensor 2
len(x) #length of x
#can also access length via shape func. shape is a tuple that indicates tensor's
#length along each axis
x.shape

#Matrices
A = torch.arange(6).reshape(3,-1)
A
#To transpose (aka flip rows and columns):
A.T

#symmetric matrices are a subset of square matrices that are equal to their own
#transposes, but not all of them are equal to each other
B = torch.tensor([[1,2,3],[4,5,6],[3,4,5]])
print(B, "\n", B.T)

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 4, 5]]) 
 tensor([[1, 4, 3],
        [2, 5, 4],
        [3, 6, 5]])


In [ ]:
torch.arange(24).reshape(2,3,4)

#tensor arithmetic
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A+B

#elementwise product of two matrices is called their Hadamard product:
#only works when matrices are the same size
A*B

a = 2
X = torch.arange(24).reshape(2,3,4)
a+X, (a*X).shape

#Reduction
#calculate sum of tensor's elements
x = torch.arange(3, dtype=torch.float32)
x, x.sum()
A.shape, A.sum(axis=0).shape
A.sum(axis=1).shape

#this is equal to the sum because it results in a vector from
A.sum(axis=[0,1]) == A.sum()

#Calculate mean by dividing the sum by the total number of elements
A.mean(), A.sum()/A.numel()

#Also works for calculating the mean to reduce a tensor along a specific axis
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [ ]:
#Non-reduction sum
#Its usefult o keep the number of axes unchanged when invoking the function
#for calcuating mean or sum, this matters when broadcasting
sum_A = A.sum(axis=1,keepdims=True)
sum_A, sum_A.shape

#sum_A keeps its two axes after summing each row
#dividing A by sum_A with boradcasting results in a matrix where each row
#sums up to 1
A / sum_A

#cumulative sum of elements uses cumsum function. Does not reduce input tensor
#along any axis
#this calculates the cumulative sum of axis 0 (row by row)
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [ ]:
#Dot Products
#X transpose Y is also known as inner product <x,y>
y = torch.ones(3,dtype=torch.float32)
x, y, torch.dot(x,y)
#can also calcualte dot product of 2 vectors by performing elementwise
#multiplication followed by a sum
torch.sum(x * y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))